Shopper app/accounts page
sikwong2/amazon pull request #154
Opened 2024-09-03 04:57 UTC by weifengtan

- Created a popover when hovering over the name to display list of stuff to press
- Created Account page 
- Created a Coming Soon page for things that are coming soon

![Screenshot 2024-09-02 at 9 53 35 PM](https://github.com/user-attachments/assets/68b623ce-153c-498a-acc2-ae83a88da6b8)

![Screenshot 2024-09-02 at 9 55 02 PM](https://github.com/user-attachments/assets/200b8459-e5c9-477c-bef1-0940acd9029f)

![Screenshot 2024-09-02 at 9 55 41 PM](https://github.com/user-attachments/assets/6cc88482-3181-48ea-a78f-f5d54679d90e)

![Screenshot 2024-09-02 at 9 55 57 PM](https://github.com/user-attachments/assets/7ec83d89-4a57-441c-ba7a-e8a97adca5b2)

2024-09-03 07:03 UTC, 6YuQing6 commented on shopper-app/src/views/ComingSoon.tsx
> +        <h1> COMING SOON </h1>
translation

2024-09-03 07:30 UTC, 6YuQing6 requested changes

2024-09-03 07:30 UTC, 6YuQing6 commented on shopper-app/src/components/SignInButton.tsx
> +          Sign In
translation

2024-09-03 07:30 UTC, 6YuQing6 commented on shopper-app/src/components/SignOutButton.tsx
> +            <Typography color="text.secondary"> Account holder </Typography>
translation

2024-09-03 07:30 UTC, 6YuQing6 commented on shopper-app/src/components/SignOutButton.tsx
> +        <a onClick={handleSignOut} className='link-no-underline'> Sign Out </a>
translate

2024-09-03 07:30 UTC, 6YuQing6 commented on shopper-app/src/components/SignOutButton.tsx
> +      <h1 style={{ fontSize: '17px', fontWeight: 'bold' }}>Your Account</h1>
translate

2024-09-03 07:30 UTC, 6YuQing6 commented on shopper-app/src/components/TopBar.tsx
> +//	)
remove comments

2024-09-03 07:30 UTC, 6YuQing6 commented on shopper-app/src/views/Account.tsx
add translation

2024-09-03 07:30 UTC, 6YuQing6 commented on shopper-app/src/components/AccountCards.jsx
> +export default function OutlinedCard({ image, alt, title, description, onClick }) {
make mouse into pointer onclick

2024-09-03 07:30 UTC, 6YuQing6 commented on shopper-app/src/components/TopBar.tsx
> +	//const signInButton = (
remove comments

2024-09-03 07:31 UTC, weifengtan commented on shopper-app/src/components/AccountCards.jsx
> +export default function OutlinedCard({ image, alt, title, description, onClick }) {
no

2024-09-03 07:42 UTC, nochoy requested changes
Missing translations, using vanilla HTML elements + CSS instead of MUI, lacking mobile responsiveness

2024-09-03 07:42 UTC, nochoy commented on shopper-app/src/components/AccountCardBox.jsx
> +        break;
account is no longer SPA

2024-09-03 07:42 UTC, nochoy commented on shopper-app/src/components/AccountCardBox.jsx
> +export default function OutlinedCard({ title, list }) {
name of file and default export should be the same name. Also, `src/components/AccountCards.jsx` also has  a default export with the same name. Someone who has not worked on this code should know what these components are based off of their name

2024-09-03 07:42 UTC, nochoy commented on shopper-app/src/components/SignInButton.tsx
> +  //pageContext.setPage()
remove

2024-09-03 07:42 UTC, nochoy commented on shopper-app/src/components/SignInButton.tsx
> +        break;
account is no longer SPA

2024-09-03 07:42 UTC, nochoy commented on shopper-app/src/components/SignInButton.tsx
> +  ];
translations

2024-09-03 07:42 UTC, nochoy commented on shopper-app/src/components/SignInButton.tsx
> +    <h1 style={{ fontSize: '17px', fontWeight: 'bold' }} > Your Lists </h1>
translations

2024-09-03 07:42 UTC, nochoy commented on shopper-app/src/components/SignInButton.tsx
> +        marginTop: 'px'
change to 0

2024-09-03 07:42 UTC, nochoy commented on shopper-app/src/components/SignInButton.tsx
> +        marginTop: 'px'
or remove

2024-09-03 07:42 UTC, nochoy commented on shopper-app/src/components/SignOutButton.tsx
> +        break;
account is no longer SPA

2024-09-03 07:42 UTC, nochoy commented on shopper-app/src/components/SignOutButton.tsx
> +  }
not used?

2024-09-03 07:42 UTC, nochoy commented on shopper-app/src/components/TopBar.tsx
> +//	)
remove

2024-09-03 07:42 UTC, nochoy commented on shopper-app/src/styles/links.css
remove this

2024-09-03 07:42 UTC, nochoy commented on shopper-app/src/pages/index.tsx
> +      {pageContext.page === 'account' && <Account/>}
account is no longer SPA

2024-09-03 07:42 UTC, nochoy commented on shopper-app/src/pages/_app.tsx
> +import "../styles/links.css"
remove

2024-09-03 07:42 UTC, nochoy commented on shopper-app/src/views/Account.tsx
> +      <h1> Your Account </h1>
translation

2024-09-03 07:42 UTC, nochoy commented on shopper-app/src/views/Account.tsx
> +        break;
account is longer SPA

2024-09-03 07:42 UTC, nochoy commented on shopper-app/src/views/Account.tsx
> +      </Grid>
150+ lines of repeated code. Try putting this stuff into a list like your other code

2024-09-03 07:42 UTC, nochoy commented on shopper-app/src/views/Account.tsx
> +      </Grid>
repeated code

2024-09-03 07:42 UTC, nochoy commented on shopper-app/src/views/ComingSoon.tsx
> +      <TopBar></TopBar>
<TopBar/>

2024-09-03 07:42 UTC, nochoy commented on shopper-app/src/views/ComingSoon.tsx
> +        <h1> COMING SOON </h1>
translation

2024-09-03 07:42 UTC, nochoy commented on shopper-app/src/views/ComingSoon.tsx
> +      <div style={{display: 'flex', justifyContent: 'center', flexDirection: 'column', alignItems: 'center'}}>
use MUI's box instead of div

2024-09-06 04:31 UTC, weifengtan commented on shopper-app/src/views/ComingSoon.tsx
> +      <TopBar></TopBar>
topbar tag

2024-09-06 04:40 UTC, nochoy requested changes
- [ ] remove bold styling from "Your Account" and logo card titles 
- [ ] get correct gray text color from Amazon
- [ ] Prime logo cutoff
- [ ] Fix font size for popover
- [ ] Fix these borders
![image](https://github.com/user-attachments/assets/19269910-8f18-44ed-bd63-6cb98fe13f88)

- [ ] 
- [ ] 
- [ ] mobile responsiveness

2024-09-06 04:40 UTC, nochoy commented on shopper-app/src/components/AccountCardBox.jsx
> +              </a>
use custom link component

2024-09-06 04:40 UTC, nochoy commented on shopper-app/src/components/SignOutButton.tsx
> +      onClick={handleSignOut}
onClick should go to account page

2024-09-06 04:40 UTC, nochoy commented on shopper-app/src/components/SignInButton.tsx
> +        onClick={handleOpen}
onClick should go to account page

2024-09-10 07:23 UTC, 6YuQing6 requested changes

2024-09-10 07:23 UTC, 6YuQing6 commented on shopper-app/src/components/SignInButton.tsx
> +        console.log('hover')
remove

2024-09-10 07:23 UTC, 6YuQing6 commented on shopper-app/src/components/SignInButton.tsx
> +          console.log('clicked')
remove

2024-09-10 07:23 UTC, 6YuQing6 commented on shopper-app/src/components/SignOutButton.tsx
> +        console.log('hover')
remove

2024-09-10 07:23 UTC, 6YuQing6 commented on shopper-app/src/components/SignOutButton.tsx
> +        console.log('clicked')
remove

2024-09-10 07:24 UTC, 6YuQing6 commented on shopper-app/src/components/SignInButton.tsx
> +        console.log('hover')
remove

2024-09-17 04:51 UTC, nochoy commented on shopper-app/src/views/Account.tsx
> +        break;
^^^

2024-09-17 04:53 UTC, nochoy approved these changes

2024-09-17 05:12 UTC, merged